name: "TNLWorlds"
version: "2.0"
api-version: "1.13"
author: "NonSwag"
main: net.nonswag.tnl.world.Worlds
website: https://www.thenextlvl.net/
depend:
  - TNLListener
load: POSTWORLD
commands:
  world:
